"""Godot offline translation display hook runner.

This runner deliberately does not perform live API translation. It preloads a
translation checkpoint generated by the pipeline and lets the Frida script
replace text at display/text-layout boundaries when the game is running.
"""
from __future__ import annotations

import argparse
import json
import logging
import re
import subprocess
import sys
import time
from pathlib import Path

try:
    import frida
except Exception:
    frida = None

repo_root = Path(__file__).resolve().parent.parent
if (repo_root / "config.py").exists():
    sys.path.insert(0, str(repo_root))

try:
    from utils.logger import get_logger, info, setup_logger, warning
except Exception:
    _fallback_logger = logging.getLogger("godot_display_hook")

    def setup_logger() -> None:
        logging.basicConfig(
            level=logging.INFO,
            format="[%(asctime)s] %(levelname)s: %(message)s",
            datefmt="%H:%M:%S",
        )

    def get_logger() -> logging.Logger:
        return _fallback_logger

    def info(message: str) -> None:
        _fallback_logger.info(message)

    def warning(message: str) -> None:
        _fallback_logger.warning(message)


_BBCODE_RE = re.compile(r"\[/?[A-Za-z_][^\]]*\]")
_BBCODE_TAG_RE = re.compile(r"\[[^\]]+\]")
_CHOICE_RE = re.compile(r"^\s*-\s+")
_DIALOGIC_SPEAKER_RE = re.compile(r"^\s*[^:\n]{1,120}\([^:\n)]{1,160}\)\s*:\s*(.+)$", re.S)
_SENTENCE_RE = re.compile(r"[^.!?\u3002\uff01\uff1f\u2026]+(?:[.!?\u3002\uff01\uff1f\u2026]+|$)")


def _clean_visible_text(text: str) -> str:
    value = str(text or "").replace("\r\n", "\n").replace("\r", "\n")
    value = value.replace("\\n", "\n")
    value = _BBCODE_RE.sub("", value)
    value = _CHOICE_RE.sub("", value)
    value = re.sub(r"[ \t\u3000]+", " ", value)
    value = re.sub(r"[ \t\u3000]*\n[ \t\u3000]*", "\n", value)
    return value.strip()


def _add_variant(out: dict[str, str], source: str, target: str) -> None:
    source = str(source or "").strip()
    target = str(target or "").strip()
    if source and target and source != target:
        out.setdefault(source, target)


def _is_safe_early_godot_text(item: dict) -> bool:
    file_value = str(item.get("file") or "").replace("\\", "/").lower()
    key_value = str(item.get("key") or "").lower()
    if not file_value:
        return False
    if file_value.startswith(".godot/") or "/.godot/" in file_value:
        return False
    if file_value.endswith((".dtl", ".dialogue")):
        return True
    if "timeline" in file_value and (
        key_value.startswith(("text_", "dlg_", "choice_", "line_"))
        or key_value in {"text", "dialogue", "choice"}
    ):
        return True
    return False


def _add_preload_variants(out: dict[str, str], original: str, translated: str) -> None:
    _add_variant(out, original, translated)
    _add_variant(out, original.strip(), translated.strip())
    _add_variant(out, _clean_visible_text(original), _clean_visible_text(translated) or translated)
    if original.lstrip().startswith("- "):
        _add_variant(out, _CHOICE_RE.sub("", original).strip(), _CHOICE_RE.sub("", translated).strip())
    _add_bbcode_segment_variants(out, original, translated)
    _add_dialogic_body_variants(out, original, translated)
    _add_sentence_chunk_variants(out, original, translated)


def _bbcode_visible_segments(text: str) -> list[str]:
    if "[" not in text or "]" not in text:
        return []
    segments: list[str] = []
    pos = 0
    for match in _BBCODE_TAG_RE.finditer(text):
        chunk = text[pos:match.start()]
        if chunk.strip():
            segments.append(chunk)
        pos = match.end()
    tail = text[pos:]
    if tail.strip():
        segments.append(tail)
    return segments


def _add_bbcode_segment_variants(out: dict[str, str], original: str, translated: str) -> None:
    source_segments = _bbcode_visible_segments(original)
    target_segments = _bbcode_visible_segments(translated)
    if not source_segments or len(source_segments) != len(target_segments):
        return
    if len(source_segments) > 24:
        return
    for source, target in zip(source_segments, target_segments):
        if not source.strip() or not target.strip() or source.strip() == target.strip():
            continue
        _add_variant(out, source, target)
        _add_variant(out, source.strip(), target.strip())
        _add_variant(out, _clean_visible_text(source), _clean_visible_text(target) or target)


def _dialogic_body(text: str) -> str:
    match = _DIALOGIC_SPEAKER_RE.match(str(text or ""))
    if match:
        return match.group(1).strip()
    return ""


def _translated_dialogic_body(text: str) -> str:
    value = str(text or "").strip()
    for sep in ("：", ":"):
        if sep in value:
            head, tail = value.split(sep, 1)
            if 1 <= len(head.strip()) <= 120 and tail.strip():
                return tail.strip()
    return value


def _add_dialogic_body_variants(out: dict[str, str], original: str, translated: str) -> None:
    source = _dialogic_body(original)
    if not source:
        return
    target = _translated_dialogic_body(translated)
    if not target:
        return
    _add_variant(out, source, target)
    _add_variant(out, _clean_visible_text(source), _clean_visible_text(target) or target)
    _add_bbcode_segment_variants(out, source, target)
    _add_sentence_chunk_variants(out, source, target)


def _sentence_chunks(text: str) -> list[str]:
    value = _clean_visible_text(text)
    if not value or len(value) < 8:
        return []
    chunks = [m.group(0).strip() for m in _SENTENCE_RE.finditer(value)]
    return [chunk for chunk in chunks if len(chunk) >= 5]


def _add_sentence_chunk_variants(out: dict[str, str], original: str, translated: str) -> None:
    source_chunks = _sentence_chunks(original)
    target_chunks = _sentence_chunks(translated)
    if not source_chunks or len(source_chunks) != len(target_chunks):
        return
    if len(source_chunks) > 12:
        return
    for source, target in zip(source_chunks, target_chunks):
        _add_variant(out, source, target)


def _load_preload_map(path: Path | None) -> dict[str, str]:
    return _load_preload_maps(path)[0]


def _load_preload_maps(path: Path | None) -> tuple[dict[str, str], dict[str, str]]:
    if not path or not path.exists():
        return {}, {}
    data = json.loads(path.read_text(encoding="utf-8-sig"))
    raw_items: list[tuple[str, str]] = []
    structured_items: list[dict] = []
    if isinstance(data, dict) and isinstance(data.get("translations"), dict):
        raw_items = [(str(k or ""), str(v or "")) for k, v in data["translations"].items()]
    elif isinstance(data, dict) and isinstance(data.get("items"), list):
        for item in data["items"]:
            if not isinstance(item, dict):
                continue
            structured_items.append(item)
            raw_items.append((str(item.get("original") or ""), str(item.get("translated") or "")))
    elif isinstance(data, dict):
        for k, v in data.items():
            if not isinstance(v, (dict, list)):
                raw_items.append((str(k or ""), str(v or "")))
    elif isinstance(data, list):
        for item in data:
            if isinstance(item, dict):
                raw_items.append((str(item.get("original") or ""), str(item.get("translated") or "")))

    out: dict[str, str] = {}
    early: dict[str, str] = {}
    for original, translated in raw_items:
        if not original or not translated or original == translated:
            continue
        _add_preload_variants(out, original, translated)
    for item in structured_items:
        original = str(item.get("original") or "")
        translated = str(item.get("translated") or "")
        if not original or not translated or original == translated:
            continue
        if _is_safe_early_godot_text(item):
            _add_preload_variants(early, original, translated)
    return out, early


def _is_process_running(device, pid: int) -> bool:
    try:
        return any(proc.pid == pid for proc in device.enumerate_processes())
    except Exception:
        return False


def _find_cjk_font() -> Path | None:
    try:
        from core.open_source_fonts import ensure_source_han_sans
        font = ensure_source_han_sans()
        if font:
            return font
    except Exception:
        pass
    for raw in (
        r"C:\Windows\Fonts\SourceHanSansCN-Regular.otf",
        r"C:\Windows\Fonts\SourceHanSansSC-Regular.otf",
        r"C:\Windows\Fonts\NotoSansCJKsc-Regular.otf",
        r"C:\Windows\Fonts\NotoSansSC-Regular.otf",
        r"C:\Windows\Fonts\NotoSansSC-VF.ttf",
    ):
        path = Path(raw)
        if path.exists():
            return path
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Godot local translation display hook")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("exe", nargs="?", type=Path, help="Game executable to launch")
    group.add_argument("--attach", type=int, metavar="PID", help="Attach to an existing game process")
    parser.add_argument("--preload", type=Path, help="translation_checkpoint.json or a JSON translation map")
    parser.add_argument("--capture", type=Path, help="Write missed runtime text to JSONL")
    parser.add_argument("--log-file", type=Path, help="Write hook diagnostics to this UTF-8 log file")
    parser.add_argument("--no-live-translate", action="store_true", help="Compatibility flag; live API calls are never used")
    parser.add_argument("--progressive", action="store_true", help="Replace typewriter prefixes progressively. Disabled by default.")
    parser.add_argument("--overlay", action="store_true", help="Draw translations in an external transparent overlay instead of replacing Godot text.")
    parser.add_argument("--overlay-file", type=Path, help="Live JSON file used by the overlay.")
    parser.add_argument("--cjk-font", type=Path, help="TTF/TTC/OTF font used by the embedded Godot font hook.")
    parser.add_argument("--src", default="auto")
    parser.add_argument("--tgt", default="zh-CN")
    args = parser.parse_args()

    setup_logger()
    if frida is None:
        print("Python package 'frida' is not installed. Install it with: pip install frida", file=sys.stderr)
        return 1

    if args.log_file:
        args.log_file.parent.mkdir(parents=True, exist_ok=True)
        handler = logging.FileHandler(args.log_file, encoding="utf-8-sig", mode="w")
        handler.setLevel(logging.DEBUG)
        handler.setFormatter(logging.Formatter("[%(asctime)s] %(levelname)s: %(message)s", datefmt="%H:%M:%S"))
        get_logger().addHandler(handler)
        info(f"Godot hook log: {args.log_file}")

    preload, early_preload = _load_preload_maps(args.preload)
    info(f"预加载 Godot 显示层译文 {len(preload)} 条，早期安全替换 {len(early_preload)} 条")
    if not preload:
        warning("Godot 显示层 hook 没有预加载译文；本次只会记录捕获/漏命中文本")

    cjk_font = args.cjk_font if args.cjk_font and args.cjk_font.exists() else _find_cjk_font()
    if cjk_font:
        info(f"Godot 内嵌字体 hook 使用: {cjk_font}")
    else:
        warning("Godot 内嵌字体 hook 未找到系统中文字体")

    device = frida.get_local_device()
    spawned_pid = None
    if args.attach:
        pid = args.attach
        info(f"附加到 Godot PID {pid}")
    else:
        exe = Path(args.exe)
        if not exe.exists():
            print(f"Executable not found: {exe}", file=sys.stderr)
            return 2
        spawned_pid = device.spawn([str(exe)], cwd=str(exe.parent))
        pid = spawned_pid
        info(f"已创建 {exe.name} (PID {pid})，正在安装 Godot 显示层 hook")

    session = device.attach(pid)
    overlay_proc = None
    overlay_file = args.overlay_file
    if args.overlay and overlay_file is None:
        if args.log_file:
            overlay_file = args.log_file.parent / "godot_overlay_live.json"
        else:
            overlay_file = Path(args.exe).parent / "_translation_meta" / "godot_overlay_live.json"
    if args.overlay and overlay_file:
        try:
            overlay_file.parent.mkdir(parents=True, exist_ok=True)
            overlay_file.write_text(json.dumps({"text": ""}, ensure_ascii=False), encoding="utf-8")
            overlay_script = Path(__file__).with_name("runtime_overlay.py")
            if not overlay_script.exists():
                overlay_script = repo_root / "core" / "runtime_overlay.py"
            overlay_proc = subprocess.Popen(
                [
                    sys.executable,
                    str(overlay_script),
                    "--profile",
                    "live-text",
                    "--target-pid",
                    str(pid),
                    "--live-file",
                    str(overlay_file),
                ],
                cwd=str(repo_root if (repo_root / "core").exists() else Path(__file__).resolve().parent),
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0) if sys.platform == "win32" else 0,
            )
            info(f"Godot 透明译文覆盖层已启动: {overlay_file}")
        except Exception as exc:
            warning(f"Godot overlay start failed: {exc}")
    script_src = Path(__file__).with_name("godot_display_hook.js").read_text(encoding="utf-8")
    script_src = (
        "var GODOT_TRANSLATION_MAP = " + json.dumps(preload, ensure_ascii=False) + ";\n"
        "var GODOT_EARLY_TRANSLATION_MAP = " + json.dumps(early_preload, ensure_ascii=False) + ";\n"
        "var GODOT_SRC_LANG = " + json.dumps(args.src, ensure_ascii=False) + ";\n"
        "var GODOT_ENABLE_PROGRESSIVE_TRANSLATION = " + json.dumps(bool(args.progressive)) + ";\n"
        "var GODOT_OVERLAY_MODE = " + json.dumps(bool(args.overlay)) + ";\n"
        "var GODOT_CJK_FONT_PATH = " + json.dumps(str(cjk_font) if cjk_font else "", ensure_ascii=False) + ";\n"
        + script_src
    )
    script = session.create_script(script_src)
    captured_seen: set[str] = set()

    def append_capture(text: str, source: str) -> None:
        if not args.capture or not text:
            return
        if text in captured_seen:
            return
        captured_seen.add(text)
        try:
            args.capture.parent.mkdir(parents=True, exist_ok=True)
            with args.capture.open("a", encoding="utf-8") as f:
                f.write(json.dumps({"text": text, "source": source, "ts": time.time()}, ensure_ascii=False) + "\n")
        except Exception as exc:
            warning(f"Godot capture write failed: {exc}")

    def update_overlay(text: str) -> None:
        if not overlay_file:
            return
        try:
            overlay_file.parent.mkdir(parents=True, exist_ok=True)
            overlay_file.write_text(json.dumps({
                "text": text,
                "font_size": 34,
                "x": 0.5,
                "y": 0.78,
            }, ensure_ascii=False), encoding="utf-8")
        except Exception as exc:
            warning(f"Godot overlay update failed: {exc}")

    def on_message(message, _data) -> None:
        if message["type"] == "error":
            warning(f"[godot hook] {message}")
            return
        if message["type"] != "send":
            return
        payload = message.get("payload", {})
        kind = payload.get("type")
        if kind == "ready":
            info(f"[godot hook] ready, preload={payload.get('count')} hooks={payload.get('hooks')}")
        elif kind == "log":
            info(f"[godot hook] {payload.get('msg')}")
        elif kind == "stats":
            info(
                f"[godot hook] replaced={payload.get('replaced')} "
                f"missed={payload.get('missed')} dwrite={payload.get('dwrite')} "
                f"gdi={payload.get('gdi')} mono={payload.get('mono')} "
                f"godot_text_server={payload.get('godot_text_server')} "
                f"godot_utf8_string={payload.get('godot_utf8_string')} "
                f"overlay_text={payload.get('overlay_text', 0)} "
                f"godot_font_data={payload.get('godot_font_data', 0)}"
            )
        elif kind == "new_text":
            append_capture(str(payload.get("text") or ""), str(payload.get("source") or ""))
        elif kind == "display_text":
            update_overlay(str(payload.get("translated") or ""))

    script.on("message", on_message)
    script.load()
    if spawned_pid is not None:
        device.resume(spawned_pid)
        info(f"已启动 {Path(args.exe).name} (PID {spawned_pid})")
    info("Godot 显示层 hook 已启动；关闭游戏窗口或 Ctrl+C 停止")

    try:
        while True:
            time.sleep(1)
            if not _is_process_running(device, pid):
                break
    except KeyboardInterrupt:
        pass
    finally:
        try:
            session.detach()
        except Exception:
            pass
        if overlay_proc is not None:
            try:
                overlay_proc.terminate()
            except Exception:
                pass
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
