"""BGI/Ethornell realtime translation runner."""
from __future__ import annotations

import argparse
import json
import logging
import subprocess
import sys
import time
from pathlib import Path

try:
    import frida
except Exception:
    frida = None

repo_root = Path(__file__).resolve().parent.parent
if (repo_root / "config.py").exists():
    sys.path.insert(0, str(repo_root))

try:
    from config import get_config
    from core.realtime_translator import RealtimeTranslator
    from utils.logger import get_logger, info, setup_logger, warning
except Exception:
    get_config = None
    RealtimeTranslator = None
    _fallback_logger = logging.getLogger("bgi_realtime")

    def setup_logger() -> None:
        logging.basicConfig(level=logging.INFO, format="[%(asctime)s] %(levelname)s: %(message)s", datefmt="%H:%M:%S")

    def get_logger() -> logging.Logger:
        return _fallback_logger

    def info(message: str) -> None:
        _fallback_logger.info(message)

    def warning(message: str) -> None:
        _fallback_logger.warning(message)


def _build_translate_fn(src: str, tgt: str):
    import httpx

    if get_config is None:
        raise RuntimeError("Live translation requires the full game-translator project. Portable BGI launchers should use --no-live-translate.")

    api_key = get_config().deepseek_api_key or get_config().openai_api_key
    if not api_key:
        raise RuntimeError("DeepSeek API Key 未配置")

    lang = {
        "ja": "Japanese",
        "zh-CN": "Simplified Chinese",
        "zh-TW": "Traditional Chinese",
    }

    def translate_one(text: str) -> str:
        response = httpx.post(
            "https://api.deepseek.com/chat/completions",
            headers={"Authorization": f"Bearer {api_key}", "Content-Type": "application/json"},
            json={
                "model": "deepseek-chat",
                "messages": [
                    {
                        "role": "system",
                        "content": (
                            f"Translate Japanese visual novel text to {lang.get(tgt, tgt)}. "
                            "Keep game control tags such as <R name> and </R> unchanged. "
                            "Output only the translation."
                        ),
                    },
                    {"role": "user", "content": text},
                ],
                "temperature": 0.1,
                "max_tokens": 512,
            },
            timeout=30,
        )
        response.raise_for_status()
        return response.json()["choices"][0]["message"]["content"].strip()

    return translate_one


def _sjis_ext_as_js_table(path: Path | None) -> str:
    if not path or not path.exists():
        return ""
    data = path.read_bytes()
    if len(data) % 2:
        raise RuntimeError(f"Invalid sjis_ext.bin length: {path}")
    chars = []
    for i in range(0, len(data), 2):
        chars.append(f"{data[i] | (data[i + 1] << 8):04x}")
    return "".join(chars)


def _load_preload_map(path: Path | None) -> dict[str, str]:
    if not path or not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))

    raw_map: dict[str, object] = {}
    if isinstance(data, dict) and isinstance(data.get("translations"), dict):
        raw_map = data["translations"]
    elif isinstance(data, dict) and isinstance(data.get("items"), list):
        for item in data["items"]:
            if not isinstance(item, dict):
                continue
            original = str(item.get("original") or "")
            translated = str(item.get("translated") or "")
            if original and translated:
                raw_map[original] = translated
    elif isinstance(data, dict):
        raw_map = data
    elif isinstance(data, list):
        for item in data:
            if not isinstance(item, dict):
                continue
            original = str(item.get("original") or "")
            translated = str(item.get("translated") or "")
            if original and translated:
                raw_map[original] = translated

    return {str(k): str(v) for k, v in raw_map.items() if k and v and str(k) != str(v)}


def main() -> int:
    parser = argparse.ArgumentParser(description="BGI/Ethornell realtime translator")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("exe", nargs="?", help="Game executable to launch")
    group.add_argument("--attach", type=int, metavar="PID", help="Attach to an existing game process")
    parser.add_argument("--preload", type=Path, help="JSON map of original text to translation")
    parser.add_argument("--sjis-ext", type=Path, help="sjis_ext.bin generated by static BGI patching")
    parser.add_argument("--no-live-translate", action="store_true", help="Only run rendering/font hooks; do not call translation API")
    parser.add_argument("--ansi-render-replace", action="store_true", help="Rewrite ANSI draw calls through Wide GDI calls for unpatched text")
    parser.add_argument("--font-create-hook", action="store_true", help="Rewrite CreateFont* calls globally; riskier, use only when draw-time font substitution is insufficient")
    parser.add_argument("--font-height-scale", type=float, default=0.95, help="Scale Chinese fallback font height during GDI font substitution")
    parser.add_argument("--log-file", type=Path, help="Write hook diagnostics to this UTF-8 log file")
    parser.add_argument("--src", default="ja")
    parser.add_argument("--tgt", default="zh-CN")
    args = parser.parse_args()

    setup_logger()
    if frida is None:
        print("Python package 'frida' is not installed. Install it with: pip install frida", file=sys.stderr)
        return 1
    if args.log_file:
        args.log_file.parent.mkdir(parents=True, exist_ok=True)
        handler = logging.FileHandler(args.log_file, encoding="utf-8-sig", mode="w")
        handler.setLevel(logging.DEBUG)
        handler.setFormatter(logging.Formatter("[%(asctime)s] %(levelname)s: %(message)s", datefmt="%H:%M:%S"))
        get_logger().addHandler(handler)
        info(f"BGI hook log: {args.log_file}")

    preload = _load_preload_map(args.preload)
    if preload:
        info(f"预加载 BGI 翻译 {len(preload)} 条")

    realtime = None
    if not args.no_live_translate:
        if RealtimeTranslator is None:
            print("Live translation requires the full game-translator project. Use --no-live-translate for portable patched games.", file=sys.stderr)
            return 1
        translate_fn = _build_translate_fn(args.src, args.tgt)
        realtime = RealtimeTranslator(translate_fn, source_lang=args.src, target_lang=args.tgt)

    device = frida.get_local_device()
    proc = None
    if args.attach:
        pid = args.attach
        info(f"附加到 PID {pid}")
    else:
        exe = Path(args.exe)
        if not exe.exists():
            print(f"Executable not found: {exe}", file=sys.stderr)
            return 1
        proc = subprocess.Popen([str(exe)], cwd=str(exe.parent))
        pid = proc.pid
        time.sleep(1.0)
        info(f"已启动 {exe.name} (PID {pid})")

    session = device.attach(pid)
    script_src = Path(__file__).with_name("bgi_realtime_hook.js").read_text(encoding="utf-8")
    script_src = (
        "var BGI_TRANSLATION_MAP = " + json.dumps(preload, ensure_ascii=False) + ";\n"
        "var BGI_SJIS_TUNNEL_TABLE = " + json.dumps(_sjis_ext_as_js_table(args.sjis_ext)) + ";\n"
        "var BGI_FONT_HEIGHT_SCALE = " + json.dumps(args.font_height_scale) + ";\n"
        "var BGI_ANSI_RENDER_REPLACE = " + json.dumps(args.ansi_render_replace) + ";\n"
        "var BGI_FONT_CREATE_HOOK = " + json.dumps(args.font_create_hook) + ";\n"
        + script_src
    )
    script = session.create_script(script_src)

    def push_result(original: str, translated: str) -> None:
        try:
            script.post({"type": "translations", "map": {original: translated}})
        except Exception:
            pass

    def on_message(message, _data) -> None:
        if message["type"] == "error":
            warning(f"[bgi hook] {message}")
            return
        if message["type"] != "send":
            return
        payload = message.get("payload", {})
        kind = payload.get("type")
        if kind == "ready":
            info(f"[bgi hook] ready, preload={payload.get('count')} tunnel={payload.get('tunnel')}")
        elif kind == "log":
            info(f"[bgi hook] {payload.get('msg')}")
        elif kind == "stats":
            info(f"[bgi hook] replaced={payload.get('replaced')} missed={payload.get('missed')} tunnel={payload.get('tunnel')}")
        elif kind == "new_text":
            text = payload.get("text", "")
            if text and realtime is not None:
                priority = 1 if len(text) < 30 else 0
                realtime.submit(text, on_result=push_result, priority=priority)

    script.on("message", on_message)
    script.load()
    info("BGI 实时翻译已启动，关闭窗口或 Ctrl+C 停止")
    try:
        while True:
            time.sleep(1)
            if proc is not None and proc.poll() is not None:
                break
    except KeyboardInterrupt:
        pass
    finally:
        try:
            session.detach()
        except Exception:
            pass

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
