"""XUnity.AutoTranslator 配置文件与语言锁覆盖说明生成。"""

from __future__ import annotations

from pathlib import Path

from utils.logger import info

from engines.xunity.diagnostics import detect_language_lock


# ---------------------------------------------------------------------------
# 配置生成
# ---------------------------------------------------------------------------

DEFAULT_TMP_SYSTEM_FONT = "Microsoft YaHei"


def generate_xunity_config(game_dir: Path, target_lang: str = "zh",
                           from_lang: str = "en", proxy_port: int = 5120,
                           tmp_font_reference: str | None = None,
                           use_engaixt_tmp_fallback: bool = False) -> Path:
    """生成 XUnity.AutoTranslator 配置文件。

    关键配置：
    - CustomTranslate 指向本地 AI 翻译代理（DeepSeek/OpenAI/Anthropic）
    - 本地 Translation_zh.txt 缓存优先命中，未命中则走在线代理
    - 目标语言简体中文，源语言自动检测
    - 启用 UI 自适应和字体替换
    """
    config_dir = game_dir / "BepInEx" / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "AutoTranslatorConfig.ini"

    # Unity 6000 IL2CPP uses our asynchronous fallback plugin because XUnity's
    # synchronous AssetBundle loader is not compatible with that runtime.
    if use_engaixt_tmp_fallback:
        tmp_fallback = ""
        tmp_mode = "EngAixt asynchronous fallback plugin"
    else:
        tmp_fallback = str(tmp_font_reference or DEFAULT_TMP_SYSTEM_FONT).strip()
        tmp_mode = "asset bundle" if tmp_font_reference else "system font"

    config = (
        "; XUnity.AutoTranslator 5.6.1 配置 — 由 game-translator 自动生成\n"
        "; 策略：本地缓存优先 + AI 翻译代理在线回退\n"
        "; 运行时先查 Translation_zh.txt，未命中则 POST 到本地代理 → DeepSeek API\n"
        "\n"
        "[Service]\n"
        "Endpoint=CustomTranslate\n"
        "\n"
        "[General]\n"
        f"Language={target_lang}\n"
        f"FromLanguage={from_lang}\n"
        "MaxCharactersPerTranslation=200\n"
        "\n"
        "[Files]\n"
        "Directory=Translation\\{Lang}\\Text\n"
        "OutputFile=Translation\\{Lang}\\Text\\_AutoGeneratedTranslations.txt\n"
        "SubstitutionFile=Translation\\{Lang}\\Text\\_Substitutions.txt\n"
        "PreprocessorsFile=Translation\\{Lang}\\Text\\_Preprocessors.txt\n"
        "PostprocessorsFile=Translation\\{Lang}\\Text\\_Postprocessors.txt\n"
        "\n"
        "[Behaviour]\n"
        "# 关闭语言范围限制：让 XUnity 翻译所有语言的文本（日/英/混合游戏均兼容）\n"
        "EnableTranslationScoping=false\n"
        "EnableUIResizing=false\n"
        "EnableBatching=true\n"
        "EnableAutoTranslator=true\n"
        "IgnoreWhitespaceInDialogue=true\n"
        "ForceSplitTextAfterCharacters=0\n"
        "TextGetterCompatibilityMode=false\n"
        "IgnoreVirtualTextSetterCallingRules=true\n"
        "IgnoreTextStartingWith=\n"
        "RedirectedResourceDetectionStrategy=None\n"
        "ParseTextTagsInTranslationCache=true\n"
        "; === 字体 ===\n"
        "OverrideFont=Microsoft YaHei\n"
        f"# TMP fallback: {tmp_mode} ({tmp_fallback})\n"
        "# System-font fallback requires TextMeshPro 3.2+; Unity 6000 IL2CPP uses EngAixt's async plugin.\n"
        "OverrideFontTextMeshPro=\n"
        f"FallbackFontTextMeshPro={tmp_fallback}\n"
        "ForceUIResizing=false\n"
        "ComponentPathBlacklistRegex=\n"
        "MaxCharactersPerTranslation=200\n"
        "MinDialogueChars=20\n"
        "CopyToClipboard=False\n"
        "MaxClipboardCopyCharacters=2500\n"
        "ClipboardDebounceTime=1.25\n"
        "UseStaticTranslations=True\n"
        "OverrideFontSize=\n"
        "FontTextMeshProSpName=\n"
        "ResizeUILineSpacingScale=\n"
        "GameLogTextPaths=\n"
        "RomajiPostProcessing=ReplaceMacronWithCircumflex;RemoveApostrophes;ReplaceHtmlEntities\n"
        "TranslationPostProcessing=ReplaceMacronWithCircumflex;ReplaceHtmlEntities\n"
        "RegexPostProcessing=\n"
        "CacheRegexPatternResults=False\n"
        "PersistRichTextMode=Final\n"
        "CacheRegexLookups=False\n"
        "CacheWhitespaceDifferences=False\n"
        "GenerateStaticSubstitutionTranslations=False\n"
        "GeneratePartialTranslations=False\n"
        "EnableSilentMode=True\n"
        "BlacklistedIMGUIPlugins=\n"
        "EnableTextPathLogging=False\n"
        "OutputUntranslatableText=False\n"
        "MaxTextParserRecursion=1\n"
        "HtmlEntityPreprocessing=True\n"
        "HandleRichText=True\n"
        "EnableTranslationHelper=False\n"
        "ForceMonoModHooks=False\n"
        "InitializeHarmonyDetourBridge=False\n"
        "OutputTooLongText=False\n"
        "TemplateAllNumberAway=False\n"
        "ReloadTranslationsOnFileChange=False\n"
        "DisableTextMeshProScrollInEffects=True\n"
        "CacheParsedTranslations=False\n"
        "\n"
        "[TextFrameworks]\n"
        "EnableUGUI=true\n"
        "EnableTextMeshPro=true\n"
        "EnableNGUI=true\n"
        "EnableUtage=true\n"
        "EnableIMGUI=true\n"
        "EnableUIElements=True\n"
        "EnableGUIText=true\n"
        "EnableTextMesh=true\n"
        "EnableSuperTextMesh=true\n"
        "EnableFairyGUI=True\n"
        "EnableDonskoyUI=True\n"
        "\n"
        "[Textures]\n"
        "TextureHashGenerationStrategy=None\n"
        "\n"
        "[Texture]\n"
        "TextureDirectory=Translation\\{Lang}\\Texture\n"
        "EnableTextureTranslation=False\n"
        "EnableTextureDumping=False\n"
        "EnableTextureToggling=False\n"
        "EnableTextureScanOnSceneLoad=False\n"
        "EnableSpriteRendererHooking=False\n"
        "LoadUnmodifiedTextures=False\n"
        "DetectDuplicateTextureNames=False\n"
        "DuplicateTextureNames=\n"
        "EnableLegacyTextureLoading=False\n"
        "TextureHashGenerationStrategy=FromImageName\n"
        "CacheTexturesInMemory=True\n"
        "EnableSpriteHooking=False\n"
        "\n"
        "[Cache]\n"
        "LoadLegacyTranslations=true\n"
        "EnablePersistentCache=true\n"
        "CacheDirectory=Translation\n"
        "\n"
        "[Http]\n"
        "UserAgent=Mozilla/5.0\n"
        "DisableCertificateValidation=True\n"
        "\n"
        "[Custom]\n"
        f"Url=http://127.0.0.1:{proxy_port}/translate\n"
        "EnableShortDelay=False\n"
        "# 禁用反垃圾检测（必须设为 True，否则 XUAT 会拦截 CustomTranslate 请求）\n"
        "DisableSpamChecks=True\n"
        "# 并发翻译数（不宜过大，避免 API 限流）\n"
        "MaxConcurrency=15\n"
        "\n"
        "[ResourceRedirector]\n"
        "PreferredStoragePath=Translation\\{Lang}\\RedirectedResources\n"
        "EnableTextAssetRedirector=False\n"
        "LogAllLoadedResources=False\n"
        "EnableDumping=False\n"
        "CacheMetadataForAllFiles=True\n"
        "\n"
        "[TranslationAggregator]\n"
        "Width=400\n"
        "Height=100\n"
        "EnabledTranslators=\n"
        "\n"
        "[Migrations]\n"
        "Enable=True\n"
        "Tag=5.6.1\n"
        "\n"
        "[Debug]\n"
        "EnablePrintHierarchy=false\n"
        "EnablePrintTextMeshPro=false\n"
        "EnableConsole=False\n"
        "\n"
    )

    config_path.write_text(config, encoding="utf-8")
    info(f"XUnity TMP fallback: {tmp_mode} -> {tmp_fallback}")
    info(f"AutoTranslatorConfig.ini 已生成: {config_path}")
    return config_path


def generate_language_override_config(game_dir: Path, force_lang: str = "Japanese") -> str | None:
    """生成语言锁覆盖说明。

    如果检测到语言锁，提示用户可通过额外 BepInEx 插件强制游戏语言。
    返回配置说明文本。
    """
    _, evidence = detect_language_lock(game_dir)
    if not evidence:
        return None

    guidance = [
        "检测到游戏可能根据系统语言切换 UI 显示语言：",
    ]
    for e in evidence:
        guidance.append(f"  - {e}")
    guidance.append("")
    guidance.append(f"如果游戏在中文系统上显示英文（而非日文原文），")
    guidance.append(f"XUAT 将拦截到英文文本，导致翻译效果不佳。")
    guidance.append("")
    guidance.append("建议：安装 ForceLanguage BepInEx 插件，将系统语言返回值强制设为日文。")
    guidance.append("  插件路径: BepInEx/plugins/ForceLanguage.dll")
    guidance.append("  或在 Windows 系统区域设置中将非 Unicode 程序语言改为日文。")

    return "\n".join(guidance)
