using BepInEx;
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Reflection;
using System.Text;
using UnityEngine;
using UnityEngine.UI;

[BepInPlugin("game-translator.ugui-overlay-guard-legacy", "Game Translator UGUI Overlay Guard Legacy", "1.0.1")]
public sealed class UGUITextOverlayGuardLegacy : BaseUnityPlugin
{
    private const string RedirectMarker = "\u180e";
    private static readonly Dictionary<Text, State> States = new Dictionary<Text, State>();
    private static readonly HashSet<Text> OverlayTexts = new HashSet<Text>();
    private static readonly Dictionary<string, string> Cache = new Dictionary<string, string>();
    private static readonly FieldInfo TextField =
        typeof(Text).GetField("m_Text", BindingFlags.Instance | BindingFlags.NonPublic);
    private bool _cacheLoaded;
    private float _nextScanAt;

    private void Awake()
    {
        Logger.LogInfo("Legacy UGUI overlay starting");
    }

    private void Update()
    {
        if (!_cacheLoaded)
        {
            LoadCache();
            _cacheLoaded = true;
            Logger.LogInfo("Legacy UGUI overlay loaded (cache-only polling mode)");
        }

        if (Time.realtimeSinceStartup < _nextScanAt)
        {
            return;
        }
        _nextScanAt = Time.realtimeSinceStartup + 0.25f;
        ScanVisibleTexts();
    }

    private sealed class State
    {
        public Text Overlay;
        public string LastOriginal = "";
        public string LastTranslated = "";
    }

    private static void ScanVisibleTexts()
    {
        Text[] texts;
        try
        {
            texts = Resources.FindObjectsOfTypeAll(typeof(Text)) as Text[];
        }
        catch
        {
            return;
        }

        if (texts == null)
        {
            return;
        }

        foreach (var source in texts)
        {
            if (source == null || OverlayTexts.Contains(source) || source.gameObject == null)
            {
                continue;
            }
            if (!source.gameObject.activeInHierarchy || !source.enabled)
            {
                continue;
            }

            var original = StripMarker(CurrentText(source));
            string translated;
            if (!TryGetTranslation(original, out translated))
            {
                RestoreSource(source);
                HideOverlay(source);
                continue;
            }

            var state = GetState(source);
            if (state.LastOriginal != original || state.LastTranslated != translated || state.Overlay == null)
            {
                state.LastOriginal = original;
                state.LastTranslated = translated;
                EnsureOverlay(source, state);
                SyncOverlay(source, state);
            }
            else if (state.Overlay != null)
            {
                state.Overlay.gameObject.SetActive(true);
            }
            HideSource(source);
        }
    }

    private static bool TryGetTranslation(string original, out string translated)
    {
        translated = "";
        if (string.IsNullOrEmpty(original))
        {
            return false;
        }

        if (Cache.TryGetValue(original, out translated))
        {
            translated = StripMarker(translated);
            return !string.IsNullOrEmpty(translated) && translated != original;
        }

        var normalized = original.Replace("\r", "\\r").Replace("\n", "\\n");
        if (Cache.TryGetValue(normalized, out translated))
        {
            translated = StripMarker(translated);
            return !string.IsNullOrEmpty(translated) && translated != original;
        }
        return false;
    }

    private static void LoadCache()
    {
        try
        {
            var root = Paths.GameRootPath;
            var candidates = new[]
            {
                CombinePath(root, "BepInEx", "Translation", "zh", "Text", "_AutoGeneratedTranslations.txt"),
                CombinePath(root, "BepInEx", "Translation", "zh", "Translation_zh.txt")
            };
            foreach (var file in candidates)
            {
                if (!File.Exists(file))
                {
                    continue;
                }
                foreach (var line in File.ReadAllLines(file, Encoding.UTF8))
                {
                    ParseCacheLine(line);
                }
            }
        }
        catch
        {
        }
    }

    private static void ParseCacheLine(string line)
    {
        if (string.IsNullOrEmpty(line) || line.StartsWith("#", StringComparison.Ordinal))
        {
            return;
        }
        var idx = FindSeparator(line);
        if (idx <= 0)
        {
            return;
        }
        var key = UnescapeKey(line.Substring(0, idx).Trim());
        var value = StripMarker(line.Substring(idx + 1).Trim());
        if (!string.IsNullOrEmpty(key) && !string.IsNullOrEmpty(value) && key != value)
        {
            Cache[key] = value;
        }
    }

    private static int FindSeparator(string line)
    {
        var escaped = false;
        for (var i = 0; i < line.Length; i++)
        {
            var ch = line[i];
            if (escaped)
            {
                escaped = false;
                continue;
            }
            if (ch == '\\')
            {
                escaped = true;
                continue;
            }
            if (ch == '=')
            {
                return i;
            }
        }
        return -1;
    }

    private static string UnescapeKey(string key)
    {
        return key.Replace("\\=", "=").Replace("\\#", "#").Replace("\\n", "\n").Replace("\\r", "\r");
    }

    private static State GetState(Text source)
    {
        State state;
        if (!States.TryGetValue(source, out state))
        {
            state = new State();
            States[source] = state;
        }
        return state;
    }

    private static void EnsureOverlay(Text source, State state)
    {
        if (state.Overlay != null)
        {
            return;
        }

        var go = new GameObject("GT_UGUI_LegacyTranslationOverlay");
        go.transform.SetParent(source.transform, false);
        var rt = go.AddComponent<RectTransform>();
        rt.anchorMin = Vector2.zero;
        rt.anchorMax = Vector2.one;
        rt.offsetMin = Vector2.zero;
        rt.offsetMax = Vector2.zero;
        rt.localRotation = Quaternion.identity;
        rt.localScale = Vector3.one;

        var overlay = go.AddComponent<Text>();
        overlay.raycastTarget = false;
        OverlayTexts.Add(overlay);
        state.Overlay = overlay;
    }

    private static void SyncOverlay(Text source, State state)
    {
        var overlay = state.Overlay;
        if (overlay == null)
        {
            return;
        }

        overlay.gameObject.SetActive(source.gameObject.activeInHierarchy && source.enabled);
        overlay.transform.SetAsLastSibling();
        SetRawText(overlay, state.LastTranslated ?? "");
        overlay.font = source.font;
        overlay.fontSize = source.fontSize;
        overlay.fontStyle = source.fontStyle;
        overlay.alignment = source.alignment;
        overlay.alignByGeometry = source.alignByGeometry;
        overlay.resizeTextForBestFit = source.resizeTextForBestFit;
        overlay.resizeTextMinSize = source.resizeTextMinSize;
        overlay.resizeTextMaxSize = source.resizeTextMaxSize;
        overlay.horizontalOverflow = source.horizontalOverflow;
        overlay.verticalOverflow = source.verticalOverflow;
        overlay.lineSpacing = source.lineSpacing;
        overlay.supportRichText = source.supportRichText;
        overlay.color = source.color;
        overlay.material = source.material;
    }

    private static void HideSource(Text source)
    {
        if (source.canvasRenderer != null)
        {
            source.canvasRenderer.SetAlpha(0f);
        }
    }

    private static void RestoreSource(Text source)
    {
        if (source.canvasRenderer != null)
        {
            source.canvasRenderer.SetAlpha(1f);
        }
    }

    private static void HideOverlay(Text source)
    {
        State state;
        if (States.TryGetValue(source, out state) && state.Overlay != null)
        {
            state.Overlay.gameObject.SetActive(false);
        }
    }

    private static string CurrentText(Text source)
    {
        try
        {
            if (TextField != null)
            {
                return TextField.GetValue(source) as string ?? "";
            }
        }
        catch
        {
        }
        return source.text ?? "";
    }

    private static void SetRawText(Text source, string value)
    {
        try
        {
            if (TextField != null)
            {
                TextField.SetValue(source, value ?? "");
                source.SetVerticesDirty();
                source.SetLayoutDirty();
                return;
            }
        }
        catch
        {
        }
        source.text = value ?? "";
    }

    private static string StripMarker(string value)
    {
        if (value != null && value.StartsWith(RedirectMarker, StringComparison.Ordinal))
        {
            return value.Substring(RedirectMarker.Length);
        }
        return value ?? "";
    }

    private static string CombinePath(params string[] parts)
    {
        if (parts == null || parts.Length == 0)
        {
            return "";
        }
        var path = parts[0] ?? "";
        for (var i = 1; i < parts.Length; i++)
        {
            path = Path.Combine(path, parts[i] ?? "");
        }
        return path;
    }
}
