"""Developer-only generator for the engine signature hint table.

The signature table is derived from a third-party GPLv3 project, so it must not
be committed or shipped with this product. It is written to build/generated/,
which is not part of any distribution, and the runtime treats a missing table as
"no extra hints".
"""
from __future__ import annotations

import os
import re
from pathlib import Path


SOURCE_REPO = Path(os.environ.get("ENGINE_SIGNATURE_SOURCE", r"C:\LunaTranslator"))
ENGINE32_DIR = SOURCE_REPO / "src" / "NativeImpl" / "LunaHook" / "LunaHook" / "engine32"
ENGINE64_DIR = SOURCE_REPO / "src" / "NativeImpl" / "LunaHook" / "LunaHook" / "engine64"


def parse_header(header_path: Path) -> dict | None:
    """Parse engine class constructor from header file."""
    try:
        content = header_path.read_text(encoding="utf-8", errors="ignore")
    except Exception:
        return None

    # Extract class name
    class_match = re.search(r"class\s+(\w+)\s*:\s*public\s+ENGINE", content)
    if not class_match:
        return None

    class_name = class_match.group(1)

    # Find check_by assignment
    check_by_match = re.search(r"check_by\s*=\s*CHECK_BY::(\w+)", content)
    if not check_by_match:
        return None

    check_by = check_by_match.group(1)

    # Skip CUSTOM and ALL_TRUE (can't parse statically)
    if check_by in ("CUSTOM", "ALL_TRUE"):
        return None

    # Extract patterns
    patterns = []

    if check_by == "FILE":
        # Single file: check_by_target = L"path/file.ext";
        match = re.search(r'check_by_target\s*=\s*L"([^"]+)"', content)
        if match:
            patterns.append(match.group(1))

    elif check_by in ("FILE_ANY", "FILE_ALL"):
        # List: check_by_target = check_by_list{L"*.ext", L"path/*.dat", ...};
        list_match = re.search(r"check_by_list\s*\{([^}]+)\}", content)
        if list_match:
            inner = list_match.group(1)
            patterns = re.findall(r'L"([^"]+)"', inner)

    elif check_by == "RESOURCE_STR":
        # Resource string check
        match = re.search(r'check_by_target\s*=\s*L"([^"]+)"', content)
        if match:
            patterns.append(match.group(1))

    if not patterns:
        return None

    # Convert Windows paths to forward slash
    patterns = [p.replace("\\", "/") for p in patterns]

    return {
        "class_name": class_name,
        "check_by": check_by,
        "patterns": patterns,
    }


def main():
    if not SOURCE_REPO.exists():
        print(f"signature source not found at: {SOURCE_REPO}")
        # ENGINE32_DIR/ENGINE64_DIR must exist under the source tree above.
        return

    engines = {}

    # Parse engine32
    if ENGINE32_DIR.exists():
        for header in ENGINE32_DIR.glob("*.h"):
            info = parse_header(header)
            if info:
                engines[info["class_name"]] = info

    # Parse engine64
    if ENGINE64_DIR.exists():
        for header in ENGINE64_DIR.glob("*.h"):
            info = parse_header(header)
            if info and info["class_name"] not in engines:  # Avoid duplicates
                engines[info["class_name"]] = info

    print(f"Parsed {len(engines)} engines with detectable signatures")

    # Generate Python file
    lines = [
        '"""Engine signature hints (generated - do not commit).',
        "",
        "Auto-generated by scripts/gen_engine_signatures.py",
        "Derived from a GPLv3 third-party signature table; not part of any distribution.",
        '"""',
        "from __future__ import annotations",
        "",
        "# check_by types:",
        "# - FILE: single file must exist",
        "# - FILE_ANY: at least one pattern must match",
        "# - FILE_ALL: all patterns must match",
        "# - RESOURCE_STR: executable contains this resource string",
        "",
        "ENGINE_SIGNATURE_HINTS: dict[str, dict] = {",
    ]

    for name, info in sorted(engines.items()):
        lines.append(f'    "{name}": {{')
        lines.append(f'        "check_by": "{info["check_by"]}",')
        lines.append(f'        "patterns": {info["patterns"]},')
        lines.append("    },")

    lines.append("}")

    output = Path(__file__).parent.parent / "build" / "generated" / "engine_signatures.py"
    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated: {output}")


if __name__ == "__main__":
    main()
